# This file was generated by PyMbs on 2014-05-23 15:21:32 UTC


from __future__ import division
from scipy import linalg, vstack, sin, cos, pi, sqrt, zeros, bmat, matrix
from scipy import arctan2 as atan2
from scipy import arctan as atan
from scipy import arcsin as asin
from scipy import arccos as acos
from scipy import sign


def Laufkatze_visual(y):

    # state
    q = matrix(y[0:2]).T

    # inputs

    # constants

    # parameter

    # visual sensor equations
    q_joint_1_Tx, q_joint_3_Ry = q.getA1()
    r_Last = matrix([[q_joint_1_Tx],[0],[0]])
    T_Traeger = matrix([[1,0,0],
        [0,1,0],
        [0,0,1]])
    r_Haken = r_Last
    T_Haken = matrix([[1,0,0],
        [0,1,0],
        [0,0,1]])
    r_Traeger = matrix(zeros( (3,1) ))
    cosq_joint_3_Ry = cos(q_joint_3_Ry)
    sinq_joint_3_Ry = sin(q_joint_3_Ry)
    T_Last = matrix([[cosq_joint_3_Ry,0,sinq_joint_3_Ry],
        [0,1,0],
        [(-sinq_joint_3_Ry),0,cosq_joint_3_Ry]])
    r_Laufkatze = r_Last
    T_Laufkatze = matrix([[1,0,0],
        [0,1,0],
        [0,0,1]])

    return {
            'r_Last' : r_Last,
            'T_Traeger' : T_Traeger,
            'r_Haken' : r_Haken,
            'T_Haken' : T_Haken,
            'r_Traeger' : r_Traeger,
            'T_Last' : T_Last,
            'r_Laufkatze' : r_Laufkatze,
            'T_Laufkatze' : T_Laufkatze,
           }
